// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCxAAnE8_mGNlkXXnEHwbevOeqEU5uGk',
    appId: '1:444122995778:web:a420dda33bfc4605b661db',
    messagingSenderId: '444122995778',
    projectId: 'mi-mejor-ser',
    authDomain: 'mi-mejor-ser.firebaseapp.com',
    storageBucket: 'mi-mejor-ser.firebasestorage.app',
    measurementId: 'G-78HP6QWS14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTebof2sV3g84uUZ33IZAXd_kCVI-G4zs',
    appId: '1:444122995778:android:162f0e0b632e9ff3b661db',
    messagingSenderId: '444122995778',
    projectId: 'mi-mejor-ser',
    storageBucket: 'mi-mejor-ser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDETPcSYFb7hgAGQFPQnu-_FVJ81Thq2yk',
    appId: '1:444122995778:ios:d3589382eac195f6b661db',
    messagingSenderId: '444122995778',
    projectId: 'mi-mejor-ser',
    storageBucket: 'mi-mejor-ser.firebasestorage.app',
    iosBundleId: 'com.example.miMejorSer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDETPcSYFb7hgAGQFPQnu-_FVJ81Thq2yk',
    appId: '1:444122995778:ios:d3589382eac195f6b661db',
    messagingSenderId: '444122995778',
    projectId: 'mi-mejor-ser',
    storageBucket: 'mi-mejor-ser.firebasestorage.app',
    iosBundleId: 'com.example.miMejorSer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCxAAnE8_mGNlkXXnEHwbevOeqEU5uGk',
    appId: '1:444122995778:web:43bd075b16f282a3b661db',
    messagingSenderId: '444122995778',
    projectId: 'mi-mejor-ser',
    authDomain: 'mi-mejor-ser.firebaseapp.com',
    storageBucket: 'mi-mejor-ser.firebasestorage.app',
    measurementId: 'G-RBHLKL6706',
  );
}
